# Generated by Django 2.2.4 on 2019-09-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.IntegerField(default=0, null=True, verbose_name='0：未删除 1：已删除')),
                ('lineName', models.CharField(max_length=50, null=True, verbose_name='业务线名')),
            ],
            options={
                'verbose_name': '业务线表',
                'db_table': 'business_line',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.IntegerField(default=0, null=True, verbose_name='0：未删除 1：已删除')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='部门名')),
            ],
            options={
                'verbose_name': '部门表',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.IntegerField(default=0, null=True, verbose_name='0：未删除 1：已删除')),
                ('groupName', models.CharField(max_length=50, null=True, verbose_name='垂直小组名')),
                ('businessLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.BusinessLine')),
            ],
            options={
                'verbose_name': '垂直小组表',
                'db_table': 'business_group',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.IntegerField(default=0, null=True, verbose_name='0：未删除 1：已删除')),
                ('moduleName', models.CharField(max_length=20, null=True, verbose_name='模块名称')),
                ('gitAddress', models.URLField(null=True, verbose_name='git地址')),
                ('caseType', models.IntegerField(verbose_name='用例类型')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('modifier', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Group')),
            ],
            options={
                'verbose_name': '配置信息',
                'db_table': 'git_config',
            },
        ),
        migrations.CreateModel(
            name='CaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_deleted', models.IntegerField(default=0, null=True, verbose_name='0：未删除 1：已删除')),
                ('moduleName', models.CharField(max_length=20, null=True, verbose_name='模块名称')),
                ('caseName', models.CharField(max_length=50, null=True, verbose_name='用例名称')),
                ('caseType', models.IntegerField(verbose_name='用例类型')),
                ('status', models.IntegerField(default=0, verbose_name='状态：0 正常，1 废弃')),
                ('casePath', models.CharField(max_length=50, null=True, verbose_name='用例路径')),
                ('modifier', models.CharField(max_length=20, null=True, verbose_name='修改人')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Group')),
            ],
            options={
                'verbose_name': '用例信息',
                'db_table': 'case_info',
            },
        ),
        migrations.AddField(
            model_name='businessline',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Department'),
        ),
    ]
