# Generated by Django 2.2.4 on 2019-10-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfo',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '废弃')], default=0, verbose_name='状态'),
        ),
    ]
